node v14 compatibility pass
entrinsik-org/assets pull request #4
Opened 2020-11-23 19:33 UTC by derek-oneill

2021-01-18 19:32 UTC, derek-oneill commented
associated PR https://github.com/entrinsik-org/i5/pull/4636

2021-02-18 21:31 UTC, gmsewell6 requested changes
see comments

Also simply running npm install rearranges package.json properly, which currently results in an always-modified version because this PRs is out of order. actually run npm install and let it fix the package.json contents organization before committing

2021-02-18 21:31 UTC, gmsewell6 commented on lib/resource.js
> +const { paths } = require('./stream-utils');
unnecessary. already used above

2021-02-18 21:31 UTC, gmsewell6 commented on lib/resource.js
> +    }
how is this necessary for node-14 compatibility

2021-05-07 18:29 UTC, derek-oneill commented on lib/resource.js
> +    }
If paths is empty you get vfs errors on startup.

2021-06-24 18:03 UTC, merged